### ISSUE TITLE
colour calibration crash in Glasgow

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#5]
Has to do with the gamma grid?

Double-check that the existing gamma grid works on the machine in Toronto. If so, this might be an issue with different versions of Numpy (it's a numpy array) or PsychoPy (maybe the way to define gamma grids has changed?). Or even different versions of Python (would be strange). If it doesn't work in Toronto, the gamma grid itself may have an error.

**Comment by thartbm** [comment]
I'm assuming the error occurs at line 1203 (`mymonitor.setGammaGrid(gammaGrid)`).

Maybe make a default monitor on the setup and then ask: `monitor.getGammaGrid()` to see what the gamma grid _should_ be?

**Comment by thartbm** [comment]
Implemented a work-around that only sets the gamma grid if `location=='toronto'`. Let me know if that is sufficient?

**Comment by thartbm** [comment]
Setting default gamma grid to a monitor object that already has it, is not an issue in Toronto.

**Comment by ClementAbb** [comment]
Here is the error message:
```
PS C:\Users\clementa\Desktop\main> & "C:\Program Files\PsychoPy_2022\python.exe" .\launcher.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
None
Traceback (most recent call last):
  File ".\launcher.py", line 4, in <module>
    bs_map.doBlindSpotMapping()
  File "C:\Users\clementa\Desktop\main\blindspot_mapping.py", line 81, in doBlindSpotMapping
    setup = localizeSetup(location=location, glasses=glasses, trackEyes=trackEyes, filefolder=None) # data path is for the mapping data, not the eye-tracker data!
  File "C:\Users\clementa\Desktop\main\EyeTracking.py", line 1291, in localizeSetup
    ET = EyeTracker(tracker           = tracker,
  File "C:\Users\clementa\Desktop\main\EyeTracking.py", line 58, in __init__
    self.setEyetracker(tracker)
  File "C:\Users\clementa\Desktop\main\EyeTracking.py", line 93, in setEyetracker
    self.setupEyeLink()
  File "C:\Users\clementa\Desktop\main\EyeTracking.py", line 285, in setupEyeLink
    mymonitor = monitors.Monitor(name='EL_temp',
TypeError: __init__() got an unexpected keyword argument 'gammaGrid'
```

**Comment by thartbm** [comment]
That makes no sense to me. I can use the keyword 'gammaGrid' on my end...

Either way, I've just removed it completely from the code (shouldn't be necessary).

The other solution would be to not specify it when creating the monitor object. so we're not using an unexpected keyword. And then use the setGammGrid() method of the monitor object later on. The current API indeed doesn't show the keyword, but it does still have the method... so maybe the API has changed between our versions of PsychoPy.
