### ISSUE TITLE
gazeInFixationWindow does not work in Glasgow

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/EyeTracking#7]
Works in Toronto, so I'm suspecting it's an issue with how tracker.lastsample() handles data from the EyeLink. E.g. it could not come from the eyelink in the expected format, or the conversion parameters are wrong or applied incorrectly.

Please add this just before the return statement in self.__EL_lastsample(): `print([gpos, o, p, data])` to see where the issue is.

**Comment by ClementAbb** [comment]
See 

[logfile.txt](https://github.com/Intrepid-2a/EyeTracking/files/14539674/logfile.txt)

**Comment by ClementAbb** [comment]
The times with 'None' are when I looked away from the screen (and could actually move the dot).

**Comment by thartbm** [comment]
So for (line 102) example: `[[-5.750000000000057, 1.600006103515625], array([959.5, 539.5]), 0.031409087025785605, array([-30.31762125, -16.89494772])]`

Has very low pixel values, which should be at some corner of the screen... upper left iirc. But. The X coordinate is negative, which is highly unlikely, and should be to the left of the screen. Am I misunderstanding the coordinate system that the EyeLink gives us? The one thing I can imagine is that [0,0] is actually the center of the screen even in gpos, so we should not correct for that at all. Do you happen to know?

**Comment by ClementAbb** [comment]
It might be the case, these sort of values are consistent with what we get with Glasgow's eyetracking code.
This still doesn't explain why the fixation is considered to be correct when there is no gaze recorded.

**Comment by thartbm** [comment]
Indeed. The LiveTrack tells me whether or not each eye could be tracked, but the EyeLink code doesn't. I have made the assumption (based on what, I don't remember: info from you or from the web somewhere) that if the EyeLink doesn't see anything, it will not return 2 values. You can see that the __EL_lastsample function first checks if gpos is a list or a tuple, and if not, it returns two NaNs. But that appears never to happen, so the assumption is probably wrong, and we need a different check. Ideas? How would you have normally checked this?

For now, I am at least removing the correction for the origin of the screen (addition off o).

**Comment by ClementAbb** [comment]
I think it's a matter of what is in gpos in each case.
We do check the same thinkg: valid_gaze_pos = isinstance(gpos, (tuple, list))
However the gpos we get from iohub's getLastGazePosition() seems to be a summary of your gpos, something like [4.3499755859375, -18.300018310546875] with just the average position between left and right eye, or None.

This might correspond to the first element of the list in your gpos:
[[126.0, -448.29998779296875], array([959.5, 539.5]), 0.031409087025785605, array([-26.17947404, -31.02589578])]
[None, array([959.5, 539.5]), 0.031409087025785605, array([nan, nan])]

In which case a quick fix would be to apply the test to gpos[0] instead

**Comment by thartbm** [comment]
The first thing in the list is the same gpos. The second is the centre of the screen, the third number is a pixels/dva scale and the third array (fourth thing) is the position on the screen in dva, when applying the centre of the screen as offset, and the scaling from pixels to dva to the gpos.

So you can see that if gpos is None, the returned eye position is a set of NaNs. That part works. It's the conversion from pixels to dva that psychopy is not doing for us automagically. Gpos itself is supposed to be in pixels, which is useless. But I think the offset is applied, whereas the scaling is not. Now I wonder if the direction of the Y-axis is also normal for psychopy or normal in hardware coordinates.

Let me think of the most useful and quick test to see what needs to be done to get everything in the same coordinate system.

**Comment by ClementAbb** [comment]
Ok, then everything makes more sense.

The transformation that you apply to the coordinates changes None to array([nan, nan]), which is (1) a list, so not caught by the valid_gaze_pos test, (2) apparently not caught either by your test of the central coordinates, probably because of some weird nan behaviour. Therefore, from the current code's point of view, that is a valid fixation, and I can move the dots when I'm not looking.

Solution to both (1) and (2) is changing the valid_gaze_pos filter to spot any nan instead. Then we are left only with the issue of coordinates.

**Comment by thartbm** [comment]
I'm pretty sure that an array is not a list:

`In [3]: a = np.array([np.nan, np.nan])

In [4]: isinstance(a, list)
Out[4]: False
`

Same for tuple. Which does not mean that the code testing if gaze is in the window is correct... The strange thing is that for me it does work: if I look away from central fixation, I can not adjust the blind spot marker properties. Similarly, in the distance task it stops the trial and shows the # thing. This makes me think it's something particular to the EyeLink code, but it could be some interaction as well. I'll have to test things through in detail.

**Comment by thartbm** [comment]
OK, there are potential issues with the function checking it. I'll invert the logic, which will make it take a it more time and will make the code more complicated (more chances to make errors), but I think it will capture the idea of the test better. Rather than starting with infix is True and switching to False on any failed test, we will (kind of) start with False, and set to True if it passes all tests.

Note: I currently also allow it to use only the right or only the left eye (or both separately, instead of the average). I think I will now do it such that all available samples should be within the window. This is not that relevant for this project since we'll use the average, but it might become interesting in future projects. So if you have any objections/insights I can still change stuff around now.

**Comment by thartbm** [comment]
Here's the new function, does that make sense to you?

```
    def gazeInFixationWindow(self):

        sample = self.lastsample()
        check_samples = self.getSamplesToCheck()
        
        for cs in check_samples:
            if cs in sample.keys():
                if any(np.isnan(sample[cs])):
                    return(False) # return False if there is a nan value
                d = np.sqrt(np.sum(np.array(sample[cs])**2))
                if d > 2:
                    return(False) # return false if the distance from fixation is larger than 2
            else:
                return(False) # return false if any of the samples that need to be checked are not in the data

        return(True) # should only get here if all samples exist, are not nans, and are within the fixation window
```

**Comment by thartbm** [comment]
Oops, hardcoded to 2 degrees... should use the soft limit.

**Comment by ClementAbb** [comment]
I'm ok to test it if it makes sense to you and you think it's in a good state for this.

**Comment by ClementAbb** [comment]
Good news: it seems to be working properly now! So no conversion and catching missing fixations seems to do the trick.

It's still complaining quite a lot so you might want to have a look:
`PS C:\Users\clementa\Desktop\main> & "C:\Program Files\PsychoPy_2022\python.exe" .\launcher.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
None
NOTE: not storing any files since filefolder is not a string
displayAPI: init_net() start use_tcp_only=0
displayAPI: Connecting
IOHUB_DEVICE_EXCEPTION.Error: Could not retrieve sample rate modes from EyeLink Host. EyeTracker.setSamplingRate None
ERROR: setEyesToTrack: Failed to get supported modes.
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\visual\shape.py:251: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "circle":
TypeError: an integer is required (got type NoneType)
TypeError: an integer is required (got type NoneType)
TypeError: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\devices\keyboard\win32.py", line 318, in _getIOHubEventObject
    key, char = self._getKeyCharValue(event)
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\devices\keyboard\win32.py", line 210, in _getKeyCharValue
    key = KeyboardConstants._getKeyName(event)
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\constants.py", line 952, in _getKeyName
    phkey = keyEvent.Key.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\devices\keyboard\win32.py", line 318, in _getIOHubEventObject
    key, char = self._getKeyCharValue(event)
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\devices\keyboard\win32.py", line 210, in _getKeyCharValue
    key = KeyboardConstants._getKeyName(event)
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\constants.py", line 952, in _getKeyName
    phkey = keyEvent.Key.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
TypeError: an integer is required (got type NoneType)
2.3047  WARNING         Monitor specification not found. Creating a temporary one...
2.3049  WARNING         Monitor specification not found. Creating a temporary one...
Calibration returned:  {'message': 'validation_result: 0.26 2.22 -3.07  0.33 -0.47 -9.08', 'result': 1000}
C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\visual\shape.py:251: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "circle":
file_size = 3806572
total_wbytes = 3806572
displayAPI: Disconnect
ioHub Server Process Completed With Code:  0`

**Comment by thartbm** [comment]
OK good.

That is a lot of complaining. Exit codes that are not 0 on Linux / in C mean that fatal errors happened, so if IoHub exits with value 0, that sounds good to me. Although they may have assigned it a different meaning.

A lot of the messages are about things being NoneType instead of a number. It doesn't what those things are though, so it's pretty hard doing anything about it (will skip for now).

A lot of the other lines seem more to be reports that a key was pressed and handled by some system.

These two lines worry me:

```
IOHUB_DEVICE_EXCEPTION.Error: Could not retrieve sample rate modes from EyeLink Host. EyeTracker.setSamplingRate None
ERROR: setEyesToTrack: Failed to get supported modes.
```
As they seem to indicate some issue with connecting to the EyeLink host computer. However, I _think_ we are setting the sampling rate and eyes to track correctly, so I will leave those lines as they are for now.

Finally, there is this message:

`NOTE: not storing any files since filefolder is not a string`

Which means that the task (whichever one it is) didn't plan on storing any eye-tracker data. If this file is from blind spot mapping, it might be that I'm NOT checking whether or not any files should be stored when initializing the EyeLink, and it could be defaulting to the standard filename, which then appears in the standard directory as well.

**Comment by ClementAbb** [comment]
I'm only testing blind spot mapping, so that would make sense.
